project:
  type: website
  output-dir: docs
  
website:
  title: "shinykorea"
  favicon: img/shiny.png
  navbar:
    right:
      - text: ğŸŒŸ HOME
        href: index.qmd
      - text: ğŸ–¼ ì‡¼ì¼€ì´ìŠ¤
        href: showcase.qmd
      - text: ğŸ“° ì´ì „ëª¨ì„
        href: previous.qmd
      - text: ğŸ“ ì»¤ë®¤ë‹ˆí‹° ì†Œê°œ
        href: about.qmd
      - icon: github
        href: https://github.com/shinykorea/Meetup
        target: _blank
  page-footer: 'shinykorea. since 2019, All rights reserved | made with quarto with â¤ï¸'
			
format:
  html:
    theme: simplex
    css: css/styles.css
    toc: true

execute: 
  freeze: true
  